### ISSUE TITLE
Cannot use super() in test cases

### ISSUE THREAD

**Issue by nigelbabu** [loadtheaccumulator/glusto#11]
Because obj is rewritten to an empty string in [carteplex.py](https://github.com/loadtheaccumulator/glusto/blob/master/glusto/carteplex.py#L151), I can't use the standard python pattern of using `super()` to call the base class functions. I have to use `im_func`. This is changing to be `__func__` in python3 and will make moving over more difficult than it should be.

**Comment by loadtheaccumulator** [comment]
Hey @nigelbabu, Any ETA on testing in your environment? It's been awhile since I tested it on the Gluster tests I was working with at the time, but would like that rubberstamp before merging.

**Comment by nigelbabu** [comment]
The upstream CI environment is not setup for testing separate branches of Glusto easily. I would suggest having Vijay test this.

**Comment by loadtheaccumulator** [comment]
Vijay ran tests. It looks good. There was an unrelated hang, but I'd like a clean run all the same. This should go in tomorrow.
