### ISSUE TITLE
License for the repo?

### ISSUE THREAD

**Issue by mykaul** [loadtheaccumulator/glusto#14]
I see the license in the code and in https://github.com/loadtheaccumulator/glusto/blob/master/examples/templates/license.txt , but it's not in the root directory of the project (or Github doesn't display it?). Can you please add it?

**Comment by loadtheaccumulator** [comment]
Hey Yaniv,
Maybe a stray when I moved from bitbucket early on. I can definitely add it.
Cheers, Jonathan
