### ISSUE TITLE
Configurability to cartesian product

### ISSUE THREAD

**Issue by nigelbabu** [loadtheaccumulator/glusto#17]
By default, a glusto class with `@runs_on()` decorator does a cartesian product. I want to be able to configure that. In the context of GCS (Gluster for Container Storage), I want to run the same tests, but only where the volume type is `replicated` (and perhaps `distributed-replicated`?) and mount type is `fuse`.

This is not currently possible and the lack of this feature is a blocker for testing Gluster for GCS with our existing Glusto tests.

**Comment by loadtheaccumulator** [comment]
So when running for Gluster use the @runs_on() as configured in GlusterBaseClass today. When running as a GCS test, run only a specific subset as defined in either the base class or a config item. Is that a correct understanding? If so, it may already be possible via the configuration in GlusterBaseClass, but we can take a closer look at best options.

**Comment by nigelbabu** [comment]
I spoke to Vijay yesterday. It appears this is already possible in configuration. So I'm going to close this unless the testing determines I'm wrong.
