### ISSUE TITLE
test requirements are not specified

### ISSUE THREAD

**Issue by mbukatov** [loadtheaccumulator/glusto#4]
Test requirements are not specified anywhere. Eg. when I try to run tests, it fails on missing `xmlrunner` module:

```
$ py.test-2
========= test session starts ========= 
platform linux2 -- Python 2.7.11 -- py-1.4.30 -- pytest-2.7.3

... <full output skipped> ...

tests/test_glusto_configs.py:18: in <module>
    import xmlrunner
E   ImportError: No module named xmlrunner

... <full output skipped> ...

```

Since I'm not familiar with pytest enough, I'm not sure how exactly should this be fixed. On the other hand, it's clear that having all requirements, including test ones, is very useful for CI and packaging.

One option would be to [integrate pytest with setup.py](http://pytest.org/latest/goodpractices.html#integrating-with-setuptools-python-setup-py-test-pytest-runner) (which would allow us to list test dependencies in `tests_require`), the other would be to specify how to run pytest in tox config file.

**Comment by loadtheaccumulator** [comment]
I added unittest-xml-reporting to setup.py yesterday-ish when it threw the same error running inside a fresh container environment. This "should" be resolved. I'll take a close look today with installs in a fresh environment to see if I can reproduce. Let me know if you are still seeing it with the latest.

**Comment by mbukatov** [comment]
Oh, you are right. I was confused because I tried to execute the tests in a wrong way.
